const keywords = [
    "Depression",
    "Anxiety",
    "Stress",
    "Therapy",
    "Counseling",
    "Mental health",
    "Psychiatrist",
    "Psychologist",
    "Bipolar disorder",
    "Schizophrenia",
    "Obsessive-compulsive disorder (OCD)",
    "Post-traumatic stress disorder (PTSD)",
    "Self-care",
    "Self-esteem",
    "Support groups",
    "Medication",
    "Panic attacks",
    "Social anxiety",
    "Phobias",
    "Suicidal thoughts",
    "Bipolar depression",
    "Eating disorders",
    "Self-harm",
    "Substance abuse",
    "Grief",
    "Trauma",
    "Coping strategies",
    "Stress management",
    "Mental health awareness",
    "Wellness",
    "Emotional well-being",
    "Behavioral therapy",
    "Cognitive-behavioral therapy (CBT)",
    "Mindfulness",
    "Meditation",
    "Relaxation techniques",
    "Sleep disorders",
    "Addiction recovery",
    "Supportive therapy",
    "Family therapy",
    "Group therapy",
    "Positive psychology",
    "Mental health stigma",
    "Mental health education",
    "Crisis helplines",
    "Emotional support",
    "Psychotherapy",
    "Anger management",
    "Emotional intelligence",
    "Mental health first aid",
    "Guidance",
    "Assistance",
  ];

  module.exports = keywords;  
  